name: "Tests"

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  fail-fast: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: xdebug
          php-version: 8.3
      - name: Install dependencies
        uses: ramsey/composer-install@v3
      - name: Run unit tests
        run: composer run test -- --coverage-clover=coverage.xml || true
      - name: Run benchmark tests
        run: composer run phpbench || true
